spring:
  application:
    name: studentSpringBootDemo
  # conncection pool
  datasource:
    url: jdbc:mysql://localhost:3306/student?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Hong_Kong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# server config
server:
  port: 8080
  error:
    include-message: always

# myBatis-plus
myBatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.studentSpringBootDemo.entity
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# logging
logging:
  level:
    com.example.studentSpringBootDemo: debug